"""
Django settings for storyzer project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import json
import os
from pathlib import Path
from configparser import ConfigParser
from manage import api_host

# Read config.ini file
config = ConfigParser()
config.read('config.ini')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!!bl9nrzxgz=+^ox9f8ie$x90-z1(guu5h$9d4y*ufyqmkm^1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

API_HOST = api_host

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'drf_yasg',
    'corsheaders',
    # 'storyzerapi',
    'storyzerapi.apps.StoryzerapiConfig'
]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

with open('keywords.json', 'r', encoding='utf-8') as f:
    SCENARIO_KEYWORDS = json.loads(f.read())

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]
CSRF_TRUSTED_ORIGINS = (
    'http://localhost:8000',
    'http://127.0.0.1:8000',
)
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://storyzer.kr",
]
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
CORS_ALLOW_HEADERS = (
    'access-control-allow-credentials',
    'access-control-allow-origin',
    'access-control-request-method',
    'access-control-request-headers',
    'accept',
    'accept-encoding',
    'accept-language',
    'authorization',
    'connection',
    'content-type',
    'dnt',
    'credentials',
    'host',
    'origin',
    'user-agent',
    'X-CSRFToken',
    'csrftoken',
    'x-requested-with',
)
APPEND_SLASH = False

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config['EMAIL']['USER']
EMAIL_HOST_PASSWORD = config['EMAIL']['PASSWORD']

OPENAI_API_KEY = config['OPENAI']['API_KEY']

ROOT_URLCONF = 'storyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storyzer.wsgi.application'


# Vertex AI
PROJECT = config['VERTEX_AI']['PROJECT']
LOCATION = config['VERTEX_AI']['LOCATION']
VOTE_ENDPOINT = config['VERTEX_AI']['VOTE_ENDPOINT']
REVENUE_ENDPOINT = config['VERTEX_AI']['REVENUE_ENDPOINT']
CLASSIFICATION_ENDPOINT = config['VERTEX_AI']['CLASSIFICATION_ENDPOINT']
CREDENTIALS = 'credentials.json'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config['DB']['NAME'],
        'USER': config['DB']['USER'],
        'PASSWORD': config['DB']['PASSWORD'],
        'HOST': config['DB']['HOST'],
        'PORT': '3306',
    }
}

VERIFICATION_EMAIL_TEMPLATE = '''
                      Storyzer Verification Email
                      
                      Verification link: {}
                      
                      Click the link above to verify your account.
                      '''


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'storyzerapi.User'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHATGPT = {
    "system_prompt":{
        "translate_en": """
        I want you to act as a translator. 
        I will give you a sentence in any other language, 
        and you will translate it into English.
        No matter what language the sentence is in, you will translate it into English.
        No need to speak descriptive sentences, just translate the sentence into English.
        If the given sentence is in English, just repeat it.
        """,
        "scenario_analysis": """
        너는 시나리오 명평론가야.
        내가 주는 json데이터를 바탕으로 다음과 같은 형식으로 분석해서 출력해줘.
        []괄호 안의 내용은 추가적인 지시사항이야.
        불필요한 \는 제거해줘.

        입력하신 영화의 제목은 {title}이고, "[{scenario}를 요약 분석한 뒤 한국어로 번역하여 출력]"의 내용을 담고 있는 영화입니다.
        예상 수익은 [{revenue}를 000,000,000 형식으로 바꿔줘]달러이며, 입력하신 예산의 [{budget}을 000,000,000 형식으로 바꿔줘]달러[와/과 중 선택하여 출력] 비교하여 [{revenue}와 {budget}을 비교하여 매우 낮은/낮은/적정/높은/매우 높은 중 하나를 선택하여 출력]수익을 거둘 것으로 예상됩니다.
        예상되는 평점은 [{vote_average}는 소수점 둘째자리까지 표기]점이며, [{vote_average}/10점을 기준으로 기대에 못미치는/평범한/훌륭한 중 하나를 선택하여 출력] 시나리오로 판단됩니다. 
        입력하신 시나리오와 유사한 타입의 영화들이 주로 사용한 키워드로는 {type_keyword} 등이 있습니다. 더 나은 시나리오를 작성하기 위해서 위와 같은 키워드를 추가적으로 사용해 보시는 것을 추천드립니다.
        입력하신 영화의 장르는 {genres}이며, 해당 장르 영화의 평균 수익과 평점은 [{genre_average}에서 {genres}에 있는 값과 일치하는 key를 선택한 뒤 'revenue' key의 'mean'과 'vote_average' key의 'mean'을 출력]과 같습니다. 
        해당 장르와 비교하여 [바로 앞 문장을 분석한 뒤 내가 입력한 {genre_average}에 있는 값을 비교하여 개선해야할/평이한/우수한 중 하나를 선택하여 출력] 영화로 예상됩니다.
        """,
        "scenario_classification": """
        I want you to act as a scenario classifier.
        I will give you a sentence, and you will classify it into one of the following categories.
        You don't have to speak descriptive sentences, just classify the sentence into one of the following categories.
        If the given sentence is repeating the same sentence, it's not a scenario, just say 'not a scenario'.
        If the given sentence is classified it's not a scenario, just say 'not a scenario'.
        If the given sentence is classified as a scenario, just say 'scenario'.
        """,
    }
}